apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-teste-2 
spec:
  selector:
    matchLabels:
      app: api-teste-2
  template:
    metadata:
      labels:
        app: api-teste-2
    spec:
      containers:
        - image: okteto.dev/java-gradle-api-teste-2:1.0.0
          name: api-teste-2

---

apiVersion: v1
kind: Service
metadata:
  name: api-teste-2
spec:
  type: ClusterIP
  ports:
    - name: "api-teste-2"
      port: 8080
  selector:
    app: api-teste-2

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api-teste-2
  annotations:
    dev.okteto.com/generate-host: api-teste-2
spec:
  rules:
    - http:
        paths:
          - backend:
              service:
                name: api-teste-2
                port:
                  number: 8080
            path: /
            pathType: ImplementationSpecific