{
 "title": "Kong Simplified Metrics - api-teste-2",
 "description": "Dashboard that graphs metrics exported via Prometheus plugin in Kong (http://github.com/kong/kong)",
 "tags": [
  "api-teste-2",
  "manged by vkpr",
  "vkpr",
  "kong"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  { "title": "Requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Request per second",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(kong_http_requests_total{route=\"vkpr.api-teste-2.api-teste-2-service-0.rest.apr.vee.codes.8080\"}[1m])) by (route)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request per second by status code",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(kong_http_requests_total{route=\"vkpr.api-teste-2.api-teste-2-service-0.rest.apr.vee.codes.8080\"}[1m])) by (route,code)",
     "legendFormat": "{{code}}"
    }
   ]
  },
  { "title": "Latencies ", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Upstream Time across ",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(kong_upstream_latency_ms_bucket{route=\"vkpr.api-teste-2.api-teste-2-service-0.rest.apr.vee.codes.8080\"}[1m])) by (route,le))",
     "legendFormat": "p90-{{route}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(kong_upstream_latency_ms_bucket{route=\"vkpr.api-teste-2.api-teste-2-service-0.rest.apr.vee.codes.8080\"}[1m])) by (route,le))",
     "legendFormat": "p95-{{route}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(kong_upstream_latency_ms_bucket{route=\"vkpr.api-teste-2.api-teste-2-service-0.rest.apr.vee.codes.8080\"}[1m])) by (route,le))",
     "legendFormat": "p99-{{route}}"
    }
   ]
  },
  {
   "title": "Request Time ",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 9 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(kong_request_latency_ms_bucket{route=\"vkpr.api-teste-2.api-teste-2-service-0.rest.apr.vee.codes.8080\"}[1m])) by (route,le))",
     "legendFormat": "p90-{{route}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(kong_request_latency_ms_bucket{route=\"vkpr.api-teste-2.api-teste-2-service-0.rest.apr.vee.codes.8080\"}[1m])) by (route,le))",
     "legendFormat": "p95-{{route}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(kong_request_latency_ms_bucket{route=\"vkpr.api-teste-2.api-teste-2-service-0.rest.apr.vee.codes.8080\"}[1m])) by (route,le))",
     "legendFormat": "p99-{{route}}"
    }
   ]
  },
  {
   "title": "Kong Proxy Latency ",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 9 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(kong_kong_latency_ms_bucket{route=\"vkpr.api-teste-2.api-teste-2-service-0.rest.apr.vee.codes.8080\"}[1m])) by (route,le))",
     "legendFormat": "p90-{{route}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(kong_kong_latency_ms_bucket{route=\"vkpr.api-teste-2.api-teste-2-service-0.rest.apr.vee.codes.8080\"}[1m])) by (route,le))",
     "legendFormat": "p95-{{route}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(kong_kong_latency_ms_bucket{route=\"vkpr.api-teste-2.api-teste-2-service-0.rest.apr.vee.codes.8080\"}[1m])) by (route,le))",
     "legendFormat": "p99-{{route}}"
    }
   ]
  },
  { "title": "Bandwidth", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Ingress per service/route",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(kong_bandwidth_bytes{direction=\"ingress\", route=\"vkpr.api-teste-2.api-teste-2-service-0.rest.apr.vee.codes.8080\"}[1m])) by (route)",
     "legendFormat": "{{route}}"
    }
   ]
  },
  {
   "title": "Egress per service/route",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 7, "y": 17 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(kong_bandwidth_bytes{direction=\"egress\", route=\"vkpr.api-teste-2.api-teste-2-service-0.rest.apr.vee.codes.8080\"}[1m])) by (route)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Bandwidth",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 17 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(kong_bandwidth_bytes{route=\"vkpr.api-teste-2.api-teste-2-service-0.rest.apr.vee.codes.8080\"}[1m])) by (route)",
     "legendFormat": "{{route}}"
    }
   ]
  }
 ]
}